#!/bin/sh

for file in `ls`; do
    # Get type
    case "$file" in
    *.mp4 | *.mov )
        type="vid"
        ;;
    *.jpg | *.HEIC )
        type="pic"
        ;;
    *)
        type="Unknown"
        ;;
    esac

    if [ -z "$type" ]; then
        echo "Invalid type: $type"

        exit 1
    fi

    # Get time
    echo "$file ($type)"
    read time

    if [ -z "$time" ]; then
        echo "Bad time: $time"

        exit 1
    fi


    if [ "$type" = "pic" ]; then
        if [ -z "$timeOffset" ]; then
            exiftool \
                -IDF0:ModifyDate="$time" \
                -ExifIFD:DateTimeOriginal="$time" \
                -ExifIFD:CreateDate="$time" \
                -overwrite_original \
                "$file"
        else
            exiftool \
                -IDF0:ModifyDate="$time" \
                -ExifIFD:DateTimeOriginal="$time" \
                -ExifIFD:CreateDate="$time" \
                -ExifIFD:OffsetTime="$timeOffset" \
                -ExifIFD:OffsetTimeOriginal="$timeOffset" \
                -ExifIFD:OffsetTimeDigitized="$timeOffset" \
                -overwrite_original \
                "$file"
        fi
    fi

    if [ "$type" = "vid" ]; then
        if [ -z "$timeOffset" ]; then
            exiftool \
                -QuickTime:CreateDate="$time" \
                -QuickTime:ModifyDate="$time" \
                -overwrite_original \
                "$file"
        else
            exiftool \
                -QuickTime:CreateDate="$time" \
                -QuickTime:ModifyDate="$time" \
                -Keys:CreationDate="$time""$timeOffset" \
                -overwrite_original \
                "$file"
        fi
    fi

    echo "\nPress any key to continue..."
    read
    clear
done
