#!/bin/bash
#
# Modified from: http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html
# 
# Takes a .mov file and creates a .gif with the same name

palette="/tmp/palette.png"

# TODO: parameterize fps and scale
filters="fps=15,scale=900:-1:flags=lanczos"

ffmpeg -v warning -i "$1" -vf "$filters,palettegen" -y $palette
ffmpeg -v warning -i "$1" -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y "${1/.mov/.gif}"
