#!/bin/bash
# Compacts then exports a VirtualBox VM
#
# Usage: vbox-export <vm name> <ssh info>
# Example: vbox-export "my-vm" "-p 2222 user@host"
# Or with SSH config: vbox-export "my-vm" "myhost"

if [ -z "$1" ]; then
    printf "Missing VM name.\n"
    exit 1
fi

if [ -z "$2" ]; then
    printf "Missing SSH info.\n"
    exit 1
fi

if ! VBoxManage showvminfo "$1" --machinereadable | grep -q 'VMState="running"'; then
    printf "# Starting VM...\n"
    VBoxManage startvm "$1"
fi

printf "\n# Writing big empty file...\n"
eval "ssh -t $2 sudo dd if=/dev/zero of=/var/tmp/bigemptyfile bs=4096k"
eval "ssh -t $2 sudo rm -v /var/tmp/bigemptyfile"

printf "\n# Stopping VM...\n"
VBoxManage controlvm "$1" acpipowerbutton

printf "Waiting for VM \"$1\" to shutdown...\n"
while ! VBoxManage showvminfo "$1" --machinereadable | grep -q 'VMState="poweroff"'; do
    sleep 1
done
printf "VM \"$1\" has been successfully shutdown.\n"

printf "\n# Compacting VM...\n"
VBoxManage modifymedium --compact "$HOME/VirtualBox VMs/$1/$1.vdi"

printf "\n# Exporting VM...\n"
VBoxManage export "$1" -o "$HOME/Desktop/$1.ova"

printf "\n# Done\n"
du -sh "$HOME/Desktop/$1.ova"
