#!/bin/sh
#
# Prints the number of files for each extension
# Copied from https://stackoverflow.com/a/55317141/8917446

find * -type f | rev | cut -d. -f1 | rev | tr '[:upper:]' '[:lower:]' | sort | uniq -c | sort -rn
