#!/bin/sh
#
# Recursively lists exifdata
#-csv \

echo "CreateDate\t\tDateCreated\tFileName"

exiftool \
    -T \
    -api MissingTagValue=".                 ."\
    -recurse \
    -quiet \
    -xmp:createDate \
    -xmp:datecreated \
    -fileName \
    --ext json \
    --ext txt \
    --ext csv \
    .
